export const SECTIONS = [
  {
    key: 'overview',
    label: 'Overview',
    path: '/overview',
    icon: 'LayoutDashboard',
    hasDropdown: false,
  },
  {
    key: 'finances',
    label: 'Finances',
    path: '/finances',
    icon: 'Landmark',
    hasDropdown: true,
    tabs: [
      { label: 'Finance', path: '/finances' },
      { label: 'Cash & Banking', path: '/finances/cash-banking' },
      { label: 'Income Check', path: '/finances/income-check' },
      { label: 'Payables', path: '/finances/payables' },
      { label: 'Supplier Ledger', path: '/finances/supplier-ledger' },
      { label: 'Media Gap', path: '/finances/media-gap' },
      { label: 'Reconciliation', path: '/finances/reconciliation' },
    ],
  },
  {
    key: 'performance',
    label: 'Performance',
    path: '/performance',
    icon: 'BarChart2',
    hasDropdown: true,
    tabs: [
      { label: 'Performance', path: '/performance' },
      { label: 'Leads', path: '/performance/leads' },
      { label: 'Buyers', path: '/performance/buyers' },
      { label: 'Suppliers', path: '/performance/suppliers' },
      { label: 'States', path: '/performance/states' },
      { label: 'Campaigns', path: '/performance/campaigns' },
      { label: 'Lead Quality', path: '/performance/lead-quality' },
    ],
  },
  {
    key: 'ads',
    label: 'Ad Intelligence',
    path: '/ads',
    icon: 'Megaphone',
    hasDropdown: true,
    tabs: [
      { label: 'Ad Intelligence', path: '/ads' },
      { label: 'Creative Insights', path: '/ads/creative-insights' },
      { label: 'Spend Reconciliation', path: '/ads/spend-reconciliation' },
      { label: 'Ad-to-Lead Quality', path: '/ads/ad-to-lead-quality' },
      { label: 'Cut / Watch / Scale', path: '/ads/cut-watch-scale' },
    ],
  },
  {
    key: 'gateway',
    label: 'Lead Gateway',
    path: '/gateway',
    icon: 'Radio',
    hasDropdown: true,
    tabs: [
      { label: 'Gateway', path: '/gateway' },
      { label: 'Intake Monitor', path: '/gateway/intake' },
      { label: 'Routing Rules', path: '/gateway/routing' },
      { label: 'Delivery Logs', path: '/gateway/delivery' },
      { label: 'Supplier Feed Health', path: '/gateway/supplier-feeds' },
      { label: 'Compliance', path: '/gateway/compliance' },
      { label: 'CAPI Events', path: '/gateway/capi' },
      { label: 'Errors', path: '/gateway/errors' },
    ],
  },
  {
    key: 'system',
    label: 'Data & System',
    path: '/system',
    icon: 'Database',
    hasDropdown: true,
    tabs: [
      { label: 'Data Sources', path: '/system' },
      { label: 'Imports', path: '/system/imports' },
      { label: 'Validation', path: '/system/validation' },
      { label: 'Settings', path: '/system/settings' },
    ],
  },
];