export const SECTIONS = [
  {
    key: 'overview',
    label: 'Overview',
    path: '/overview',
    icon: 'LayoutDashboard',
    hasDropdown: false,
  },
  {
    key: 'finances',
    label: 'Finances',
    path: '/finances',
    icon: 'Landmark',
    hasDropdown: true,
    tabs: [
      { label: 'Finance Overview', path: '/finances' },
      { label: 'Bank Income', path: '/finances/bank-income' },
      { label: 'Reported vs Paid', path: '/finances/reported-vs-paid' },
      { label: 'Costs & Payables', path: '/finances/costs-payables' },
      { label: 'Supplier Cost Check', path: '/finances/supplier-cost-check' },
      { label: 'Media Spend Check', path: '/finances/media-spend-check' },
    ],
  },
  {
    key: 'performance',
    label: 'Performance',
    path: '/performance',
    icon: 'BarChart2',
    hasDropdown: true,
    tabs: [
      { label: 'Performance Overview', path: '/performance' },
      { label: 'Daily Performance', path: '/performance/daily' },
      { label: 'Buyer Performance', path: '/performance/buyers' },
      { label: 'Supplier Performance', path: '/performance/suppliers' },
      { label: 'Campaign Performance', path: '/performance/campaigns' },
      { label: 'State Performance', path: '/performance/states' },
      { label: 'Lead Quality', path: '/performance/lead-quality' },
    ],
  },
  {
    key: 'ads',
    label: 'Ad Intelligence',
    path: '/ads',
    icon: 'Megaphone',
    hasDropdown: true,
    tabs: [
      { label: 'Ads Overview', path: '/ads' },
      { label: 'Campaign Profitability', path: '/ads/campaign-profitability' },
      { label: 'Creative Insights', path: '/ads/creative-insights' },
      { label: 'Spend Reconciliation', path: '/ads/spend-reconciliation' },
      { label: 'Cut / Watch / Scale', path: '/ads/cut-watch-scale' },
    ],
  },
  {
    key: 'settings',
    label: 'Settings',
    path: '/settings',
    icon: 'Settings',
    hasDropdown: true,
    tabs: [
      { label: 'General', path: '/settings' },
      { label: 'Data Sources', path: '/settings/data-sources' },
      { label: 'Validation', path: '/settings/validation' },
      { label: 'Ad Accounts', path: '/settings/ad-accounts' },
    ],
  },
];